version: '3.4'

services:
    www:
        image: nginx:alpine
        ports:
            - "8000:80"
        deploy:
            replicas: 2
    success:
        image: alpine:3.6
        command: "sh -c 'exit 0'"
        deploy:
            replicas: 3
            restart_policy:
                condition: none
    # failure:
    #     image: alpine:3.6
    #     command: "sh -c 'exit 127'"
    #     deploy:
    #         replicas: 1
    #         restart_policy:
    #             condition: none
