parameters:

services:
    _defaults: { autowire: true, autoconfigure: true, public: false }

    App\:
        resource: '../src'

    App\Domain\DockerClient:
        alias: 'App\Infra\ShellDockerClient'